chore: bump sdk-bridge package version to support infinite token approval
nomad-xyz/nomad-app pull request #366
Opened 2022-06-02 20:35 UTC by Imti

Closes https://github.com/nomad-xyz/nomad-app/issues/110

2022-06-03 02:47 UTC, ErinHales commented
Hm, shoot.  Getting this error.  The max amount for approval is overflowing, I'm not sure why.  Maybe we need to decrease the value a bit

<img width="375" alt="Screen Shot 2022-06-02 at 8 43 35 PM" src="https://user-images.githubusercontent.com/36751902/171776781-3a366757-5800-465d-b3be-989e1f134dd3.png">

2022-06-03 02:49 UTC, ErinHales requested changes
Above comment needs to be resolved

2022-06-06 19:29 UTC, ErinHales requested changes

2022-06-06 19:29 UTC, ErinHales commented on src/views/Transfer/Transfer.pending.vue
> -      </n-text>
We need to keep this text actually. Normally there are 2 steps to a bridge transfer: `approve` and `send`.  If the user has already approved enough, then they still need to head to their wallet to approve the send transaction. The wording is a bit confusing haha, hopefully that makes sense

2022-06-07 23:40 UTC, Imti commented
Closing in favor of https://github.com/nomad-xyz/nomad-app/pull/373

2022-06-07 23:40 UTC, closed without merging